-- Starter tag vocabulary (D-066). Conservative, factual seed so Tab 4 is
-- populated and tag-classify has targets to classify into. All values are
-- editable via the Taxonomie tab; Buhara refines there. Idempotent.

INSERT INTO public.tag_vocabulary (axis, value, label_de, approved_at) VALUES
  ('brand','airtuerk-service','airtuerk Service', now()),
  ('brand','airtuerk-holidays','airtuerk Holidays', now()),
  ('brand','atbeds','atBeds', now()),
  ('brand','service-center-antalya','Service Center Antalya', now()),
  ('brand','ibe-product-suite','IBE Product Suite', now()),
  ('brand','airtuerk-apix','airtuerk APIX', now()),
  ('brand','internal-branding','Internal Branding', now()),
  ('department','service','Service', now()),
  ('department','sales','Sales', now()),
  ('department','marketing','Marketing', now()),
  ('department','it','IT', now()),
  ('department','holidays','Holidays', now()),
  ('department','beds','Beds', now()),
  ('department','antalya','Antalya', now()),
  ('department','executive','Geschäftsführung', now()),
  ('provider','amadeus','Amadeus', now()),
  ('provider','sabre','Sabre', now()),
  ('provider','confluence','Confluence', now()),
  ('provider','m365','Microsoft 365', now()),
  ('provider','supabase','Supabase', now()),
  ('provider','vercel','Vercel', now()),
  ('provider','anthropic','Anthropic', now()),
  ('provider','voyage-ai','Voyage AI', now()),
  ('topic','konti','Konti', now()),
  ('topic','storno','Storno', now()),
  ('topic','refund','Refund', now()),
  ('topic','provision','Provision', now()),
  ('topic','ticketing','Ticketing', now()),
  ('topic','iata','IATA', now()),
  ('topic','ndc','NDC', now()),
  ('topic','faq','FAQ', now()),
  ('topic','sicherheit','Sicherheit', now()),
  ('topic','onboarding','Onboarding', now()),
  ('topic','support','Support', now()),
  ('topic','abrechnung','Abrechnung', now()),
  ('airline','pegasus','Pegasus', now()),
  ('airline','sunexpress','SunExpress', now()),
  ('airline','turkish-airlines','Turkish Airlines', now()),
  ('airline','condor','Condor', now()),
  ('airline','lufthansa','Lufthansa', now()),
  ('airline','eurowings','Eurowings', now()),
  ('airline','corendon','Corendon', now()),
  ('airline','anadolujet','AnadoluJet', now())
ON CONFLICT (axis, value) DO NOTHING;
